development:
  adapter: postgresql
  database: madc_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: madc_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: madc_production
  pool: 5
  timeout: 5000
