development:
  adapter: postgresql
  database: madc_development-1
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: madc_test-1
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: madc_production-1
  pool: 5
  timeout: 5000
